name: Build and commit documentation

on:
  push:
    branches: 
      - develop
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout package
      uses: actions/checkout@v2

    - name: Install Ruby
      id: build-docs
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Build Docs
      working-directory: ./docs
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Rebuilt documentation site
        title: Rebuilt docs
        body: Automatic rebuild of the documentation site. As long as the status checks pass, this can usually just be merged without review.
        author: Toby Twigger <tobytwigger1@gmail.com>
        branch: develop
