name: Build docs and commit to build branch

on:
  push:
    branches: 
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout package
      uses: actions/checkout@v2

    - name: Install Ruby
      id: build-docs
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Build Docs
      working-directory: ./docs
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build
        
    - name: Commit assets
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        push_options: '--force'
        commit_user_name: Toby Twigger
        commit_user_email: tobytwigger1@gmail.com
        commit_message: Build documentation
        branch: build/documentation
