name: Test build of laravel translate

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        dependency-version: [prefer-lowest, prefer-stable]
        php: [7.3,7.4,8.0,8.1]
        laravel: [8.*,9.*]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}
 
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP ${{matrix.php}}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php}}


      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest


      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run test suite
        run: composer run-script test
